name: msm
description: Media Server Manager.

publish_to: "none"

version: 1.10.0+18

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.38.3

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.0
  dartssh2: ^2.13.0
  permission_handler: ^12.0.1
  filesize: ^2.0.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  go_router: ^17.0.0
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  flutter_local_notifications: ^19.5.0
  xterm: ^4.0.0
  flutter_background_service: ^5.0.2
  wake_on_lan: ^4.1.1+3
  flutter_email_sender: ^8.0.0
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  pointycastle: ^3.9.1
  basic_utils: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.14.4
  dependency_validator: ^5.0.3
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/svgs/msm.svg
    - assets/images/app_icon.png
    - shell_scripts/basic_details.sh
